spring.application.name=flujo-cicd-backend

# Base de datos H2 en memoria (solo para este proyecto base / demo)
spring.datasource.url=jdbc:h2:mem:tareasdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Consola web de H2, util para explorar los datos en http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
